language: node_js
node_js:
- 10
- 12
- "stable"

before_script:
- npm install
- cp loki_template.ini loki.ini
- cd nodepomf && npm install && cd ..
- cd server && npm install && cd ..
- node dialects/transport/dialect.loki_proxy.js
cache: npm
